# Generated by Django 4.2 on 2026-05-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_clientprofile_id_alter_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='client_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
